name: treex_app_next
description: A new Flutter project.

version: 1.1.0+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: 
  flutter_miui: 
  flare_flutter: 
  animations: 
  # TODO ^0.4.2 may have break changes in later version
  sensors: ^0.4.2
  provider: 
  flutter_markdown: 
  flutter_icons: 
  liquid_pull_to_refresh: 
  bot_toast: 
  dio: 
  connectivity: 
  qr_code_scanner: 
  qr_flutter: 
  intl: 
  folding_cell: 
  crypto: 
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: 
flutter:
  uses-material-design: true
  assets:
    - assets/treex-next.flr
flutter_intl:
  enabled: true